.flake8
piper.in
piper/ratbagd.py

No functional changes, just formatting. Style options are debatable; I don't really have any preference but it's good to have a standard for the code IMO. I went for PEP8 because it's the most used one. Checking for conformance should be done using the `flake8` tool and the configuration given in this commit, i.e. PEP8 specifies docstrings to be of 72 characters wide but since it passes flake8 it's ok.
E402 and E501 are ignored because we don't care (that much) about line length, and GObject Introspection requires us to import things as we currently do.
piper/piper.py has not been fixed as it is going to be removed eventually, when all its relevant bits have found a place in the new code.

Conform to PEP8 style guide

---

data/piper.gresource.xml
piper/application.py
piper/mousemap.py
piper/piper.py
piper/window.py

This widget implements a central part of the new UI. See [this webm](https://hjdskes.github.io/img/blog/gsoc-part-4/mousemap-interactive.webm) to get an impression for that it does (note that the styling of the highlight is outdated; it now highlights the entire button instead of just its border).
Next up will be a new window making use of this widget, stealing code from piper.py.

MouseMap: custom container widget to map the device SVG

---

piper/ratbagd.py

A quick PR that adds two things: a `Commit` method on `RatbagdDevice`, and libratbag's error codes so that Piper can easily test return values of the DBus method calls.
I've though about adding exceptions as well (i.e. `RatbagdErrorDevice(BaseException)`) but this gets nasty real quick; either every method call in the binding needs to do an `if/else` to raise the proper exception, or `_dbus_call` does this but then has the possibility of raising *all* exceptions which isn't nice from an API point of view.

Add error codes to the ratbagd bindings, plus commit method

---

data/piper.gresource.xml
data/resolutionRow.ui
data/resolutionsPage.ui
data/window.ui
piper.in
piper/gi_composites.py
piper/mousemap.py
piper/ratbagd.py
piper/resolutionrow.py
piper/resolutionspage.py
piper/window.py

This PR adds the resolutions page according to the mockups (well, mostly). It's not entirely done but I would like some feedback and discussion:
1. Libratbag doesn't yet support adding and removing resolutions (see https://github.com/libratbag/libratbag/issues/211), how do I deal with this in Piper? At the moment, the widgets are there printing a message to stdout.
2. To draw only one leader in the MouseMap in the resolutions page, I modified the SVG requirements (again...). I'm not particularly happy with this as the list of SVG requirements is already pretty long, but basically I grouped the paths and the little squares they connect to and gave this group the id `buttonX-path`. Commit https://github.com/libratbag/piper/pull/28/commits/fb068e395c076755a2c2535c12e5fa842843c0d1 should …

Add resolutions page

---

piper/resolutionspage.py

If toggling the same row twice and then toggling second row, both the first and the second row would be toggled. This commit fixes that, by resetting `last_activated_row` to `None` in case the same row is toggled.

ResolutionsPage: fix toggling the wrong row

---

piper/resolutionrow.py

Modules that need internationalization import gettext as `_`, so anonymous variables should be named `__` instead (double underscore) so as not to clash.

Rename anonymous variables from _ to __

---

piper/piper.py
piper/ratbagd.py

This is required to explicitly and immediately update the cached properties, to prevent race conditions from occurring in Piper.
I didn't connect to the [`g-properties-changed`](https://developer.gnome.org/gio/stable/GDBusProxy.html#GDBusProxy-g-properties-changed) signal, as according to the linked documentation the "local cache has already been updated when this signal fires", AKA: this won't solve the race condition, at least not if I understand the documentation correctly.

Explicitly and immediately set cached DBus properties on update

---

data/piper.gresource.xml
data/ui/LedDialog.ui
data/ui/OptionButton.ui
piper/leddialog.py
piper/ledspage.py
piper/optionbutton.py
piper/window.py

As per [the mockups](https://github.com/libratbag/piper/raw/wiki/redesign/leds.png), but dialogs instead of popovers to consistently use dialogs throughout Piper (as they are required for button mapping) and with the color selection button moved into the configuration dialog as not every mode has a configurable color.
Changes are applied only after the commit button is pressed. State in between two invocations of any configuration dialog is not remembered; not even after a commit. The former is intentional, the latter is a bug. I suspect this is due to the bindings only retrieving their properties from DBus upon instantiation, but I'll look into this after opening this PR.
Also, as noted in the code, we cannot toggle *after* the user has accepted the changes in the dialog or not toggle …

Add LED page to configure LEDs

---

piper/resolutionspage.py

See https://github.com/libratbag/libratbag/issues/202.
It wouldn't be difficult to support devices that do support individual report rates; it would simply be a matter of the following to set the active resolution's report rate only:
```diff
diff --git a/piper/resolutionspage.py b/piper/resolutionspage.py
index 9c7faa6..c0b580f 100644
--- a/piper/resolutionspage.py
+++ b/piper/resolutionspage.py
@@ -75,11 +75,11 @@ class ResolutionsPage(Gtk.Box):
def _on_report_rate_toggled(self, button, rate):
profile = self._device.active_profile
-        # TODO: currently no devices expose CAP_INDIVIDUAL_REPORT_RATE, but if
-        # so then we should check for this here and set it only on the relevant
-        # resolution.
-        for resolution in profile.resolutions:
- …
```

ResolutionsPage: set report rate for all resolutions

---

data/ui/LedDialog.ui
data/ui/OptionButton.ui
data/ui/ResolutionRow.ui
data/ui/ResolutionsPage.ui
data/ui/Window.ui

Every control widget should have a tooltip to explain its purpose.
Fixes #40

data/ui: add tooltips to control widgets

---

piper/ratbagd.py

Quite a few PRs open both here and in libratbag that now modify the bindings. We should be careful when merging all of them.
In any case, this adds exception messages to `RatbagdDBusUnavailable` so that we can print those to the user.

RatbagdDBusUnavailable: add exception message

---

.flake8
circle.yml
meson.build
piper.in

Fixes #50, by adding a `piper.devel` output next to the regular `piper` output. The regular `piper` output now doesn't have any debug or development code whatsoever, and the `piper.devel` output has two lines of code that 1) fix the Python path to import from the source directory and 2) print to the user that they're running from source.
I went for the approach that adds / moves around the least amount of files. It might be a bit abusive of Meson but I think overall the approach is quite minimal and the achieved effect is nice.

Add a piper.devel output to run from source tree

---

piper/ratbagd.py

Since this property changes not through one of our setters but internally in ratbagd, the `notify::action-type` signal isn't automatically emitted. Piper needs this to update the button labels in the mouse buttons' configuration stack page.

bindings: emit notify::action-type ourselves

---

piper/window.py

This code will definitely be changed (read: improved) once I tackle the welcome screen. For now, just print another string to `stderr` and bail.
Fixes #65.

Window: do not crash when no devices are plugged in

---

piper/application.py

The current about dialog is named `AboutDialog.ui` but is linked as `/org/freedesktop/Piper/aboutDialog.ui` in `src/application.py`. Which throws:
```
(piper.devel:6977): Gtk-ERROR **: failed to add UI: The resource at “/org/freedesktop/Piper/aboutDialog.ui” does not exist
```
This pr fixes that.

Application: change aboutDialog.ui resource path to AboutDialog.ui

---

data/ui/MousePerspective.ui
data/ui/ResolutionRow.ui
piper/mouseperspective.py
piper/ratbagd.py
piper/resolutionrow.py

This PR implements some of @hadess' suggestions from #69. I think that timeout-based commit is something we should look into and is perhaps something for a future version of Piper, but for now as a stop-gap sort of thing I went with these suggestions:
1. Disable the button when nothing has been changed
2. Make the button blue like the default button in dialogues ('suggested-action' style IIRC) when something has been changed
As for the icon, personally I'm not confused by it but if you feel that others might I'm open to switching it for something else. Perhaps we can make a custom save icon, that replaces the disk with a mouse? In any case, I much prefer an icon over text so I'd rather do that as a last resort.
The other suggestions about asking users about unsaved changes before exiting …

Make the commit button more obvious

---

data/ui/ResolutionsPage.ui

As mentioned in #91. I think this is the smallest we can make it while it still looks OK.

ResolutionsPage: reduce width of the controls

---

piper/application.py
piper/errorperspective.py
piper/mousemap.py
piper/mouseperspective.py
piper/ratbagd.py
piper/welcomeperspective.py
piper/window.py

This should go after #84.
Maybe we can show an [empty placeholder](https://developer.gnome.org/gtk3/stable/GtkListBox.html#gtk-list-box-set-placeholder) in the welcome perspective's listbox when there are no devices, instead of displaying the error perspective. This would look something like the empty search result in GNOME Control Center's keyboard panel:
Right now, Piper does the following:
Device added:
* No device connected currently → immediately configure the connected device
* Devices currently connected, in welcome perspective → add the new device to the list
* Device(s) currently connected, in mouse perspective → make the back button visible (will be added in this PR, currently not there), possibly an in-app notification if we want it
Device removed:
* Removed device is the one …

React to devices being added or removed

---

data/ui/MousePerspective.ui

Fixes #69.
@hadess [is right](https://github.com/libratbag/piper/issues/69#issuecomment-321776046).

MousePerspective: change button icon to text

---

piper/errorperspective.py
piper/mouseperspective.py
piper/welcomeperspective.py
piper/window.py

This adds another property to the perspectives, which signals whether a perspective can safely shutdown. On a delete event, the Window checks all its perspectives' properties and if one perspective signals that it cannot safely shutdown, a dialog is presented that allows the user to either shutdown ignoring any changes or to abort and commit or make other changes.
Fixes #102.

Ask for confirmation when quitting with unsaved changes

---

piper/mouseperspective.py
piper/ratbagd.py
piper/window.py

As found here https://github.com/libratbag/piper/issues/115#issuecomment-322439908.

Correctly display the error perspective if the MouseMap cannot display itself

---

piper/ratbagd.py

This prevents crashing when a device reports an unknown special action
type to libratbag, see e.g. #120.

RatbagdButton: add ACTION_SPECIAL_UNKNOWN to SPECIAL_DESCRIPTION

---

piper/mouseperspective.py
piper/ratbagd.py

See #120.
I'm not entirely sure about this, because basically we're working around broken device drivers here. If the driver is broken, it doesn't make much sense to try and continue. Maybe instead I should add a check for an active profile and resolution when the MousePerspective is being opened, and bail from there only. Or, we let things as-is and make sure our drivers work.

Do not crash if there is no active profile or resolution

---

piper/ratbagd.py

As mentioned in #119, this is just a stop-gap until libratbag
switches to an async commit (https://github.com/libratbag/libratbag/issues/269)
Fixes #119.

Ratbagd: increase timeout from 500 to 2000 milliseconds

---

data/ui/ButtonDialog.ui
piper/buttondialog.py
piper/buttonspage.py

Another take for #82; where we only allow swapping the left- and right mouse button. Until https://github.com/libratbag/libratbag/issues/233 is fixed I'm using the buttons' indices to detect whether a button is left or right (with approval from @whot).

ButtonDialog: only allow swapping left- and right buttons

---

meson.build

Now we only have one configuration structure, and only one file will be generated instead of two.

Meson: simplify development version

---

piper/mousemap.py

Since Gtk 3.18 passing a state other than the current state isn't
recommended and can apparently lead to hogging the CPU due to triggering
a loop: requesting style context triggers pixel cache refresh, which triggers
do_draw, which requests the style context that triggers the pixel cache again,
et cetera.
For background, see https://bugzilla.gnome.org/show_bug.cgi?id=760462
and the linked blog post https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/.
Note that the advice of using the gtk_render_* API doesn't work for the
MouseMap, so we have to use the suggested workaround.
Fixes #133.

MouseMap: save & restore GtkStyleContext to prevent hogging the CPU

---

data/ui/ResolutionRow.ui
piper/ratbagd.py
piper/resolutionrow.py

The same approach should work for showing and setting the default resolution (see #36) so I'll look into fixing that too. Note that this depends on an incoming patch to ratbagd.

ResolutionRow: add label to highlight the active resolution

---

piper/buttondialog.py

ButtonDialog: do not list "Unknown" in the special mappings

---

data/ui/OptionButton.ui

Otherwise it stretches the whole GUI

ui: limit the length of macros displayed in the option box

---

piper/mousemap.py

In a previous commit I added this optimization that prevents redrawing
the widget when it is reallocated: with the widget being centered,
enlarging the window does not require to redraw the widget.
However, I missed the case where the allocation actually gets smaller
(and thus the SVG is repositioned) when the width of one of the child
widgets changes, which would with this optimization result in parts of
the SVG being shifted a few pixels to the left with the remainder being
in its original position. Hence, this fixes a visual glitch in drawing
the SVG.

MouseMap: redraw on allocate

---

piper/buttondialog.py

ButtonDialog: correctly (re)initialize the current macro on Escape

---

piper/ratbagd.py

This ensures that `RatbagdProfile::notify::is-active` is fired in all instances where the property is updated, and not just on our own `set_active` method. This fixes #167.
I also added "caching" for `RatbagdProfile::is-active`, `RatbagdResolution::is-active` and `RatbagdResolution::is-default` so that the signals are only emitted on those objects where the properties actually changed, as a stop-gap for the FIXMEs in libratbag ([1](https://github.com/libratbag/libratbag/blob/bb23f68d53a5da85c195def66ec103f086b9254b/ratbagd/ratbagd-profile.c#L271), [2](https://github.com/libratbag/libratbag/blob/bb23f68d53a5da85c195def66ec103f086b9254b/ratbagd/ratbagd-resolution.c#L85) and [3]( https://github.com/libratbag/libratbag/blob/bb23f68d53a5da85c195def66ec103f086b9254b/ratbagd/ratbagd-resolution.c# …

Emit `RatbagdProfile::notify::is-active` in all instances where the property is updated

---

piper/resolutionspage.py

The radiobuttons for changing the report rate fires the 'toggled'
signal both when being set and unset. This caused the report rate
to flip when chaning the active profile.
Follow the advice in the GTK documentation and check if the button
is active in the callback function.

ResolutionsPage: fix bad toggles of report rate

---

meson_install.sh

This ensures that the icon cache will be generated when installed locally,
but will also make sure that we don't generate one when DESTDIR is set.
This helps with packaging, where packages should never provide the duplicate
"icon-theme.cache" file inside the package.
This is based around the meson build system implemented by @TingPing in
the gnome-twitch project.
Signed-off-by: Ikey Doherty <ikey@solus-project.com>

Do not generate icon-cache when DESTDIR is set

---

piper/ratbagd.py

A new LED type "wheel" was added in libratbag.
Related PR in libratbag: https://github.com/libratbag/libratbag/pull/398

sync LED type from libratbag

---

README.md

libratbag now exports a list of permitted resolutions rather than a min/max
value (and a guesswork step increment on piper's side). Use that and snap the
resolution slider to the nearest value in that list.
See https://github.com/libratbag/libratbag/pull/393
Related to #186

ResolutionsRow: snap to nearest allowed resolution value

---

piper/mousemap.py

When pressing a button and moving out of the button area with the button held
down, we get two leave events - once when actually leaving the button and once
more when the button press is released later. On the second call, the old
highlight is already None, causing a crash when we're trying to get SVG
information about it.
Fixes #185

MouseMap: if the old highlight is None, don't try to redraw

---

data/ui/LedDialog.ui
piper/leddialog.py
piper/ledspage.py
piper/ratbagd.py

libratbag/libratbag#422 introduced effect duration in ms for LEDs as opposed to effect rate in Hz, as was discussed in #175. This commit updates Piper's UI to reflect these changes.
Fixes #175.
NOTE: this depends on libratbag/libratbag#422 and should not be changed before 1) that PR is merged and 2) its changes to ratbagd.py have been synced back into Piper.

LedDialog: use new effect duration in ms

---

piper/leddialog.py

If a LED does not support e.g. 'Cycle' mode then we should
not show that page in the LED stack switcher.

Hide LED modes that are not supported

---

meson.build

I replace single quotes (') with triple quotes (''') for multiline string as they are deprecated.

meson: fix deprecated quotes

---

piper/application.py

AboutDialog: hook up the response signal to the dialog's destroy()

---

piper/welcomeperspective.py

When clicking the Quit button we should emit the delete
event to go through the checks for unapplied changes in
the delete handler on the window.
Before we had inconsisten behavior between pressing Quit
and closing Piper from e.g. gnome-shell.
The issue was discovered in #220

WelcomePerspective: delete window on quit

---

piper/mouseperspective.py
piper/welcomeperspective.py

This is a followup fix for #220. In #226 we made Piper follow the same exit path from both the Quit button and closing the program from gnome-shell (or similar). This caused the bug to be consistently exposed in both ways.
The problem was that we hit an exception in MousePerspective.can_shutdown by accessing an attribute on the device, which is not yet set. can_shutdown is a GObject.Property and these do not (can not) support exceptions. This leads to can_shutdown returning False, which Piper thinks is due to unapplied changes which it warns the user about. After accepting to exit anyway the exception is printed.
This fix is simply to check if _device is None to avoid the exception. This fixes #220 
I also included a small patch for a deprecation warning I missed in the commit in #226.

Allow shutdown with no device

---

piper/mouseperspective.py
piper/profilerow.py

libratbag stores a name for each profile since
libratbag/libratbag/pull/275
Let's use the supplied name instead of using index numbers

Use profile name from libratbag

---

piper/buttonspage.py
piper/ledspage.py
piper/mousemap.py
piper/resolutionspage.py
piper/welcomeperspective.py

On fedora 29 we get the following deprecation warnings, which
this commit fixes
/usr/lib/python3.7/site-packages/piper/mousemap.py:88: PyGIDeprecationWarning: GObject.PARAM_READABLE is deprecated; use GObject.ParamFlags.READABLE instead
GObject.PARAM_READABLE),
/usr/lib/python3.7/site-packages/piper/welcomeperspective.py:33: PyGIDeprecationWarning: GObject.SIGNAL_RUN_FIRST is deprecated; use GObject.SignalFlags.RUN_FIRST instead
"device-selected": (GObject.SIGNAL_RUN_FIRST, None, (GObject.TYPE_PYOBJECT,)),
/usr/lib/python3.7/site-packages/piper/resolutionspage.py:79: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: …

Fix deprecation warnings

---

meson.build

This is too annoying when you build in multiple different prefixes etc. and
the PATH isn't always set up. Let alone requiring distributors to install
ratbagd to build Piper.
Downgrade it to a large warning and let's hope people at least read that one.

meson: downgrade the 'ratbagd not found' to a message only

---

meson.build

Checks the ratbagd version at meson time and expresses a warning when it's not recent enough.
Up until the currently requested minimum version, ratbagd didn't have a
--version command so an error is equivalent to 'too old'.

meson.build: add hooks to check for a minimum ratbagd version

---

data/org.freedesktop.Piper.appdata.xml.in

Fixes: https://github.com/flathub/org.freedesktop.Piper/issues/1
Pretty sure that's the reason we don't show up in flathub.

data: link to flathub-compatible 16:9 screenshots in the appdata

---

README.md

Piper [has recently been added to openSUSE](https://build.opensuse.org/request/show/644078) which uses zypper as its packaging system.

Add installation via zypper to the documentation

---

data/ui/ResolutionsPage.ui

This hasn't been implemented in over a year, let's hide it from sight. Maybe
that spurns someone on to actually implement it.
It's an improvement to the GUI either way because the message printed to stdout
wouldn't be seen by most users starting the Piper through e.g. gnome shell. So
it just looks like the button is broken.

Hide the "add a resolution" button

---

piper/resolutionspage.py

Reproducer:
- click on resolution A, B
- click on the + button
- click on resolution C
Now both B and C are revealed because B is still the last row and we call
toggle reveal on it.

ResolutionsPage: reset the last row if we click the "add" button

---

data/ui/MousePerspective.ui
piper/mouseperspective.py
piper/ratbagd.py
piper/resolutionspage.py

This PR finally handles the resync signal and therefor fixes #182.
The resync signal is captured in the ratbagd bindings and emitted on the `RatbagdDevice`. The `MousePerspective` simply listens for this signal to be emitted and when it is, displays the notification overlay to inform the user that something went wrong and that the device has been restored to a previous state (which happens automagically in ratbagd).
Now we just need to get Piper to properly update itself when values change behind its back on the ratbagd side (edit: see https://github.com/libratbag/libratbag/pull/566), but that is for another PR.

Handle the Resync signal

---

piper/mousemap.py

Scaling the SVG is sufficient, since all other drawing/position operations depend on information from the SVG. With this change, Piper should work nicely on HiDPI screens.
Fixes #281.

MouseMap: scale appropriately on HiDPI screens

---

piper/mouseperspective.py

This PR includes the changes we need to make in order to work with [libratbag removing device capabilities](https://github.com/libratbag/libratbag/pull/631). Note that I didn't include the changes to ratbagd.py in this PR, nor [the changes I had to make to it in order to show profile names](https://github.com/libratbag/libratbag/pull/631#issuecomment-465549800).
It'd be good if someone could test this on a device that doesn't allow one or more of the following:
1. resolution changes
2. button remapping
3. led changes
My device supports all three and it works on here.

Update for libratbag removing device capabilities

---

piper/mouseperspective.py
piper/profilerow.py

Where the profile name is none (the empty string), fake a profile name based
on the index. This used to be done in ratbagd but was removed there with the
most recent snapshot.
Fixes #323

Fake a profile name where none exists

---

data/svgs/svg-lookup.ini

Adds an additional PID match for the MX Anywhere 2 since these mice appear to use one of several differen Bluetooth PIDs.
See libratbag/libratbag#721 and libratbag/libratbag#722

Add PID for MX Anywhere 2

---

data/svgs/svg-lookup.ini

The vendor ID I added had a typo; it should match the vendor portion of the other PIDs for this device.
See libratbag/libratbag#734

Fix PID Typo

---

data/svgs/svg-lookup.ini

Signed-off-by: Filipe Laíns <lains@archlinux.org>

data: fix wrong name for the G403 Wireless

---

data/svgs/svg-lookup.ini

Update `DeviceMatch` value for Logitech MX Master in according [with the libratbag device description](https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-MX-Master.device).
It was first mentioned in [this issue](https://github.com/libratbag/libratbag/issues/439) and I also can confirm that my MX master has `bluetooth:046d:b017` id.

Add missing device id for MX Master

---

data/ui/AboutDialog.ui.in

Jente has indicated that he doesn't find the time to keep maintaining piper.
Let's remove him from the maintainer list, primarily to save him some
misguided emails.

data: drop Jente's name from the maintainers

---

meson.build
piper.in
piper/application.py
piper/ratbagd.py
piper/window.py

This should get rid of (or at least clarify) the many many issues we see where ratbagd and piper talk different APIs and then one of them gets confused or blows up. This is supposed to be a temporary fix until we have the stable DBus API but temporary has a new meaning when things take years.
This depends on https://github.com/libratbag/libratbag/pull/775

Check ratbagd API version on startup

---

data/meson.build
data/svgs/README.md
data/svgs/check-svg.py
data/svgs/logitech-g604.svg
data/svgs/svg-lookup.ini

As mentioned in https://github.com/libratbag/libratbag/issues/832 there is no SVG file for the Logitech G604. I went ahead and created one.
I just realized it is possible to map the DPI buttons too, so I added leaders for them as well.

Added SVG for Logitech G604

---

.circleci/config.yml
meson.build

Package builds fine without development dependencies since the build process only runs ordinary python scripts. This would also make #421 unnecessary.

python development package not necessary

---

data/svgs/README.md

piper is licensed under GPLv2, not under GPLv3.

Fix license changes for svgs

---

data/svgs/check-svg.py

According to the readme height and width values from 400 to 500 are allowed, but `check-svg.py` only allows values between those to values. This PR fixes this behavior.
Signed-off-by: Stephan Lachnit <stephanlachnit@protonmail.com>

check-svg: adjust width and height ranges

---

data/meson.build
data/ui/AboutDialog.ui.in

The Debian package tracker [noticed](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/piper.html) that the builds are not reproduceable, meaning they can change under certain scenarios. I checked it and it is the copyright year in the AboutDialog, which was set to change dynamically in f2a9e5d8bbf30360ea207a4859573ef2f1b0470f. While it sounds like a good idea to not put it in the file, an old version shouldn't have a copyright note which is never than the actual release date in my opinion. I put the `copyright_years` variable below the `version_date` variable so it won't get forgotten in new releases.

Make builds reproduceable

---

data/meson.build
data/ui/AboutDialog.ui.in

Adds more readable version string.
More representative website label.
Also fixes translations against commit b02460028568c9f03b752e095264af87450badae.

AboutDialog: miscm improvements

---

piper/ratbagd.py
piper/window.py

This addresses issue libratbag/libratbag/#802 reported for libratbag by porting over the solution implemented in libratbag and adjusting the UI error message to hint at the potential permission issue.

dbus: more gracefully handle permission when connecting to the daemon

---

data/meson.build
data/svgs/logitech-mx518.svg
data/svgs/svg-lookup.ini

Adding the Logitech MX518 ([product link](https://www.logitechg.com/en-gb/products/gaming-mice/mx518-gaming-mouse.html)) SVG file & required changes to support it.
* `DeviceMatch` id taken from libratbag [here](https://github.com/libratbag/libratbag/blob/808f42360051597fe16783cd5c7a57eb194ef7d8/data/devices/logitech-MX518.device)
Can I also get a bit of guidance over an issue related to the button index vs mapping of the button dialog? The problem was also present with the fallback SVG.
I am trying to have the up and down buttons next to the wheel (button 6 and 5 in the SVG respectively) to trigger BTN_FORWARD & BTN_BACK in libinput.
The problem is that I am unable to have _"Button 6"_ assigned to _"Button 6 click"_ and _"Button 5"_ assigned to _"Button 5 click"_ for that. Instead I have …

data: Add logitech-mx518

---

data/meson.build
data/svgs/logitech-g815.svg
data/svgs/svg-lookup.ini

adds basic support for the logitech g815 keyboard
https://github.com/libratbag/piper/issues/478
I've created the svg and added the usb device id.
It still thinks its a mouse, therefore it won't let me change G1 and G2 to something other than LMB and RMB.
Weirdly, the macro tab keys (m1-3) are now also normal macro keys, as the macro tab feature is missing and I don't know how to do that.
lastly, I have to press one of the m-keys in order to get the lighting to update after clicking apply.

data: add SVG for the Logitech G815

---

data/meson.build
data/svgs/logitech-m720.svg
data/svgs/svg-lookup.ini

Add graphics and device definition for the Logitech M720 Triathlon wireless mouse.
Product page: https://www.logitech.com/en-us/product/m720-triathlon
The DeviceMatch was taken from [libratbag](https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-M720.device)
The button below the wheel is the ratchet mode switch. The "1 2 3" button switches between the three devices the mouse can be connected to.
The mouse has an additional button moulded into the thumb rest which some users report as being mapped to Alt+Tab, however I cannot reproduce this. Remapping this button also doesn't do anything but I think that's an issue with libratbag rather than Piper.

data: Add Logitech M720 Triathlon

---

data/org.freedesktop.Piper.appdata.xml.in.in

Before:
```
appstreamcli validate --pedantic data/org.freedesktop.Piper.appdata.xml.in.in
I: org.freedesktop.Piper:23: nonstandard-gnome-extension kudos
I: org.freedesktop.Piper:3: cid-missing-affiliation-gnome org.freedesktop.Piper
W: org.freedesktop.Piper:58: invalid-iso8601-date @version_date@
Validation failed: warnings: 1, infos: 2
```
After:
```
appstreamcli validate --pedantic data/org.freedesktop.Piper.appdata.xml.in.in
W: org.freedesktop.Piper:51: invalid-iso8601-date @version_date@
Validation failed: warnings: 1
```
I also marked "Piper" as non-translatable.

data: fix some appstream warnings

---

data/org.freedesktop.Piper.appdata.xml.in.in
meson.build

`GPL-2.0+` is deprecated, the SPDX recommends using `GPL-2.0-or-later` instead. Reference: https://spdx.org/licenses/ (at the bottom).

Use SPDX 3.0 license identifiers

---

piper/application.py
piper/buttondialog.py
piper/buttonspage.py
piper/devicerow.py
piper/errorperspective.py
piper/leddialog.py
piper/ledspage.py
piper/mousemap.py
piper/mouseperspective.py
piper/optionbutton.py
piper/profilerow.py
piper/resolutionrow.py
piper/resolutionspage.py
piper/svg.py
piper/welcomeperspective.py
piper/window.py

SPDX license identifiers make it easier to find out under what license a file is.
Obviously, this will only work if @Hjdskes (current copyright owner) agrees to that change.
Also, I want to put `piper/svg.py` under the GPL-2.0 like the rest of the code. This file was entirely written by @whot, so that only works if you agree as well.

Use SPDX 3 license identifiers in the code

---

data/meson.build
data/piper.1.in
meson.build

Every program should have a man page, even if it doesn't have a cli. ~~Theoretically I would add a "See also" section pointing to a man page for ratbagd, but it doesn't exist^^ (yet)~~
Can be tested with `man -l builddir/data/piper.1`.

data: add man page

---

.circleci/config.yml
meson.build
piper/ratbagd.py

Fix for https://github.com/libratbag/libratbag/issues/1017.
Looking at the code, the documentation is thankfully very helpful. First we want to know the type to convert it into a variant, to then send a `string+string+variant` via DBus, so the second format is useless.
Regarding the other commits, see #548.

flake8 fix + arch CI

---

data/svgs/svg-lookup.ini

This allows the svg to show up when the M720 is connected via bluetooth

data: add Logitech M720 bluetooth ID from libratbagd to svg

---

data/svgs/check-svg.py

I was hoping to be able to come around to this and refactor the test to introduce device types, but I haven't been able to. So just disable the minimum button count so that we can move #555 forward.

tests: check-svg: have no minimum required button count

---

.circleci/config.yml
meson.build
meson_options.txt

I want to remove all runtime dependency checks for Piper in Meson, that aren't actually required to build/install Piper.
The reasoning is pretty obvious: the build environment might not be the use environment in a lot of scenarios. For example, in Debian the package is created from a build server, that never runs Piper, however it still needs the Python `gi` module etc, which consumes unnecessary build time and should be avoided.
It also reduces the CI runtimes.

meson: remove runtime dependency checks

---

.circleci/config.yml

See https://github.com/libratbag/libratbag/commit/3f99446a1be984b78eac60e47bfd66e1c674e30c
Signed-off-by: Filipe Laíns <lains@riseup.net>

ci: temporarily disable arch

---

data/meson.build
data/svgs/logitech-g513.svg
data/svgs/svg-lookup.ini

I created an SVG for my Logitech G513 Carbon and added it's USB identifier. libratbag doesn't support all of the keys that are shown in LG G Hub for it as seen here:
But the SVG has support for all 12 function keys so they should be automatically picked up when libratbag supports them. It works perfectly for the LEDs.
I don't own the other variants of the keyboard so I don't know if their USB identifiers are different, but they all look the same so they should be fine when added.
Here's some screenshots:

Add support for the Logitech G513 Carbon Keyboard

---

data/svgs/svg-lookup.ini

The Logitech MX vertical can also be identified by this USB ID
Output of `lsusb`: 
```
Bus 001 Device 006: ID 046d:c08a Logitech, Inc. MX Vertical Advanced Ergonomic Mouse
```

Add second second USB ID for Logitech MX Vertical

---

.circleci/config.yml
data/meson.build

Currently the test gives an informational warning (doesn't fail):
```
I: org.freedesktop.Piper:3: cid-contains-uppercase-letter org.freedesktop.Piper
The component ID should only contain lowercase letters.
```
We might want to change the rDNS to `io.github.libratbag.piper`, as it is suggested by https://www.freedesktop.org/software/appstream/metainfocreator. Having a "wrong" url is a bad idea anyway since it might be possible some project on freedesktop.org will call itself Piper and use it as well (unlikely though).
I do heard that changing the component ID is potentially breaking so I'm not sure if we actually want to that (I have no idea though, but I can imagine something like ratings in the store).

meson: add test for appdata file

---

README.md

The big FAILED looks bad, especially since we're no longer using
Circle CI.

README: drop the CircleCI build status

---

data/svgs/logitech-mx-anywhere3.svg

I modified the svg for the Logitech MX Anywhere 3 to look like the Logitech MX Anywhere 3 instead of the MX Anywhere 2. I verified that it works (as much as piper works for this mouse).
One bug as shown in the screenshot below is that the path doesn't show up for button 2 and I wasn't able to fix it.
Hopefully someone can help with that, but even if not, it's still more functional than with the previous SVG (or none).

Add correct svg for MX Anywhere 3

---

data/ui/ErrorPerspective.ui
data/ui/WelcomePerspective.ui
piper/errorperspective.py
piper/welcomeperspective.py

Using a Quit button is an anti-pattern and might be confusing for users
expecting the quit button to be on the same position as of other apps'.
Note that the button is on the left and by default the close button is
on the right.

Replace Quit buttons with normal close buttons

---

.github/workflows/main.yml
meson.build
meson_install.sh

Introduced a new option `-Dscripts` for packaged builds.
Will be very useful in downstream packaging, because Koji/OBS shouldn't run `gtk-update-icon-cache` during the package build.

Modern way to handle post-installation actions

---

.flake8
meson.build

When the build directory is not _under_ the source directory then
flake8 cannot find the local config file and it will try to check
piper.in which fails per 1ed66262b77ebd9fe188894d36842527da39508a
To fix this I propose to
1. pass the config to flake8 explicitly
2. remove piper.in from the args list since it is excluded in the
flake8 config anyway
3. check the generated $build/piper.devel and $build/piper too per
1ed66262b77ebd9fe188894d36842527da39508a
4. merge the --ignore in meson.build with the config
Steps to reproduce:
```
$ meson ../build
$ ninja -C../build test
...
[17/18] Running all tests.
1/5 piper:all / files-in-git             SKIP            0.01s   exit status 77
2/5 piper / validate appdata file        OK              0.04s
3/5 piper / svg-lookup-check             OK …
```

Fix tests for out-of-source builds

---

data/svgs/svg-lookup.ini

Just received my G502 X and saw it is not yet supported. Luckily https://github.com/libratbag/piper/pull/788 already added the image, so this trivial change made the mouse usable in Piper.

Add Support for G502 X over USB

---

piper/resolutionspage.py

Show only rate buttons which was reported as supported by mouse.

resolutionspage: show available rates only

---

.github/workflows/main.yml

Might as well use something recent
May or may not help with the flake8 issues in #769

ci: bump the test image to Ubuntu 22.04

---

.github/workflows/main.yml

Node 12 is deprecated so let's bump the actions to newer versions that use Node 16. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

CI: bump some actions to newer versions

---

piper/ratbagd.py

- fix changes to IsActive potentially not being notified about
- make the profile dirty after changing report rate
This fixes the "Apply" button being disabled after changing report rate in Piper (once this file gets synchronized there).

ratbagd.py: sync with libratbag

---

data/ui/ResolutionsPage.ui
piper/resolutionspage.py

Fixes #834.
FIXME: I also noticed that if active report rate is not one of [125, 250, 500, 1000], the button for 125 would still be active. None should be active if possible.

Don't show report rate selection box if the device doesn't support it

---

piper/devicerow.py

This should probably go onto the bottom of the advanced settings page, but it would require significantly more effort.

devicerow: show device firmware version near it's name

---

po/POTFILES

There are a few other files not in the POTFILES list, but they are just helpers (svg.py and gobject.py).

po: add the "advanced" page to translatable files

---

piper/resolutionrow.py

Ideally I would like it to also show the reason for example on hover, but this is already better.

resolutionrow: disable the "disable" button for the default resolution

---

data/org.freedesktop.Piper.svg

Removes all unused mask and clip paths, crops the embedded image, optimizes file size and fixes render issues seen in KDE apps (Gwenview, Application Launcher, Application Dashboard etc.).

Fix blank app icon issues with KDE application launcher
