piper/ratbagd.py
This is a direct copy from the last `ratbagd/python/ratbagd/__init__.py`,
with the line "This file is part of ratbagd" removed, because, well,
it's not anymore.
=> Import ratbagd bindings

piper/ratbagd.py
The bindings weren't up to date, some properties, methods and capabilities were missing.
In the process, I made the bindings' classes inherit from GObject, so that the Piper code can connect to its signals and watch for property changes. The details are in the commit message of 4618ad2.
I'm not sure if there is anything missing (I modeled things off of the DBus interface as specified in [ratbagd's README](https://github.com/libratbag/ratbagd#the-dbus-interface)). I think that's fine; I'll add or adapt (or fix, it's currently untested) things when I find them to be missing while working on Piper.
One thing I did notice is that every `Ratbagd*` class instantiates a new DBus connection by inheriting from `_RatbagdDBus`. It seems unnecessary to me to have one DBus connection for each profile, …
=> Update ratbagd bindings

piper/ratbagd.py
That's what you get for not testing...
=> ratbagd: add missing commas

README.md, circle.yml, piper.in
Currently only checks for style issues.
=> Add circle.yml

piper/ratbagd.py
Fixes #16, but depends on [ratbagd#35](https://github.com/libratbag/ratbagd/pull/35/files).
=> ratbagd: add RatbagdLed class

piper/piper.py, piper/ratbagd.py
Make git master of piper work again. This possibly fixes the issue with https://github.com/libratbag/piper/issues/15 as well
=> Make piper great again

piper/ratbagd.py
https://github.com/libratbag/piper/issues/11
=> ratbagd: re-use the same dbus connection

piper/ratbagd.py
https://github.com/libratbag/libratbag/pull/209
=> ratbagd: add Themes property and GetSvg(theme) method

piper/piper.py, piper/ratbagd.py
See #35 for why, but basically this is just the Right Thing™
Sidenote: I should really start writing some tests for these, especially with the introduction of the driver-test libratbag element from https://github.com/libratbag/libratbag/pull/218
=> Always query DBus for the latest value in the bindings

piper/ratbagd.py
This is a convenient way for me to sync between the 2, but it will
allow piper to have tests too :)
Note I haven't properly tested this in piper itself, counting on you, @Hjdskes :)
=> ratbagd.py: sync with libratbag

piper/ledspage.py, piper/resolutionspage.py
This code is most likely temporarily until I get around to implementing profiles for real.
=> Make Piper rewrite work with the new bindings

piper/application.py, piper/window.py
Should go after #54. Fixes #49.
=> Application: present error dialog when ratbagd isn't running

piper/piper.py, piper/ratbagd.py
Less changes than expected :) Please do double check if I didn't miss anything. Obviously any pending changes in open Piper PRs aren't in here; I'll rebase those once this is in. I'll also open a PR on libratbag to sync this back in there too then.
=> ratbagd: sync with libratbag

data/piper.gresource.xml, data/ui/ProfileRow.ui, data/ui/Window.ui, piper/buttonspage.py, piper/ledspage.py, piper/profilerow.py, piper/ratbagd.py, piper/resolutionrow.py, piper/resolutionspage.py, piper/window.py
This PR adds support for profiles, i.e. it allows the user to switch between profiles, disable them (which hides them from the UI) and enable them (make the first disabled profile visible again).
@whot Just a WIP PR to get an ACK on the current approach before I extend it to everything.
=> Implement profiles

data/ui/ResolutionRow.ui, piper/ledspage.py, piper/resolutionrow.py
The resolution rows look quite empty now; not sure what to do with those.
=> Drop indices from the GUI

piper/resolutionspage.py
=> ResolutionsPage: fix labeling buttons related to resolutions

piper/buttonspage.py
=> ButtonsPage: apply profile cycle buttons across all profiles

meson.build, piper.in
=> Piper: check for required GTK version at runtime

piper/mouseperspective.py
=> MousePerspective: destroy profiles before adding new ones

piper/mouseperspective.py
=> MousePerspective: only consider profile dirty for commit button

piper/buttondialog.py
=> ButtonDialog: also register key releases

meson.build
=> meson: copy configuration data so we don't have to duplicate it manually

piper/ratbagd.py
As mentioned in https://github.com/libratbag/piper/issues/140#issuecomment-323543204.
=> Do not return values from setters in the bindings

data/ui/ButtonDialog.ui, piper/buttondialog.py
This required a bit of changes to the ButtonDialog's UI, so I decided to overhaul it a bit more and hopefully improve its looks.
=> ButtonDialog: add a search entry to search mappings

piper/ratbagd.py
See #140. Depends on https://github.com/libratbag/libratbag/pull/290.
=> Ratbagd: remove _dbus_call from setters

po/LINGUAS, po/sv.po
Add Swedish translation to Piper.
=> Add sv l10n

piper/devicerow.py
device is the RatbagdDevice, don't overwrite it because we're still trying to
access things like device.name
=> DeviceRow: don't overwrite "device" with the SVG

piper/ratbagd.py
See #177; [`Gio.DBusProxy::call`](https://lazka.github.io/pgi-docs/Gio-2.0/classes/DBusProxy.html#Gio.DBusProxy.call) does not raise exceptions, but [`Gio.DBusProxy::call_finish`](https://lazka.github.io/pgi-docs/Gio-2.0/classes/DBusProxy.html#Gio.DBusProxy.call_finish) does. For starters, we should thus move our catching there.
=> ratbagd: move catching exception to the right place

piper/resolutionrow.py
libratbag now exports a list of permitted resolutions rather than a min/max
value (and a guesswork step increment on piper's side). Use that and snap the
resolution slider to the nearest value in that list.
See https://github.com/libratbag/libratbag/pull/393
Related to #186
=> ResolutionsRow: snap to nearest allowed resolution value

data/led-off.svg, data/piper.gresource.xml, data/ui/LedDialog.ui, piper/leddialog.py
Ah, what a beautiful night sky...
The CSS background taken from the control-center scroll test page. Apparently
we can't use the SVG background and have to do this manually.
Fixes #45
=> Led: add an image for the led off page

meson.build
This time with the single quotes escaped
=> meson.build: fix deprecated single quotes

circle.yml
=> CircleCI: install libratbag as well

piper/devicerow.py, piper/mousemap.py, piper/ratbagd.py
Required for #235, otherwise we can't open the files. Requires https://github.com/libratbag/libratbag/pull/523 to be pulled in first.
The flatpak branch in #235 needs to be rebased on top of this one once merged, then it should all just magically work.
=> Fetch SVGs as fds, not as paths.

data/meson.build, data/org.freedesktop.Piper.appdata.xml.in, meson.build, org.freedesktop.Piper.json
Fixes #202, #236 
Edit: still missing
=> Flatpak support

README.md, piper/window.py
=> README improvements and better error handling

data/org.freedesktop.Piper.appdata.xml.in, data/ui/AboutDialog.ui.in, data/ui/ButtonDialog.ui, data/ui/ErrorPerspective.ui, data/ui/ResolutionRow.ui, data/ui/ResolutionsPage.ui
See https://developer.gnome.org/hig/stable/typography.html
=> Use Unicode typography in user-visible strings

data/ui/AboutDialog.ui.in, meson.build, po/de.po
I got reminded again why I never switch any UI to german...
=> Contributor credits and updated german translation

data/ui/MousePerspective.ui, piper/mouseperspective.py
=> mouseperspective: don't show the profile button if we only have one profile

piper/ratbagd.py, piper/window.py
Let's not crash when the daemon goes away
=> Handle daemon crashes/disappearance

data/ui/ResolutionRow.ui, piper/resolutionrow.py
This hasn't been added yet and likely won't in the foreseeable future.
See #266.
=> ResolutionRow: remove delete button

piper/ratbagd.py, piper/resolutionrow.py, piper/resolutionspage.py
This syncs piper with the new ratbagd API. Not that much to do after all, most of it is hidden away in the bindings anyway.
I think it'll be best to merge this with a merge commit btw, otherwise we have commits that don't work on master.
~Also, setting a button macro failed here,  but I think that's a libratbag issue, still investigating.~ *edit:  Multi-key macros fail, that's a HID++ 2.0 implementation limit in libratbag*
=> Sync with the new API

meson.build
=> Fix meson deprecation warning

data/svgs/svg-lookup.ini
This small patch just cleans up the device naming which is currently all over the place. Makes everything use the same clean name scheme.
=> data: cleanup svg-lookup.ini

piper/buttondialog.py, piper/buttonspage.py
=> Update the button page whenever any button mapping changes

org.freedesktop.Piper.json
See https://github.com/flathub/org.freedesktop.Piper/pull/4
=> Update Piper Flatpak to GNOME 3.32

data/svgs/svg-lookup.ini
based on 
[https://github.com/libratbag/libratbag/pull/686](url)
[https://github.com/libratbag/libratbag/issues/684](url)
=> updating deviceMatch for Logitech G Pro 

data/svgs/svg-lookup.ini
I don't think I missed anything but if anyone wants to double check, please be my guest :grin:.
=> data: adapt to Linux 5.2 for Logitech devices

piper/buttondialog.py, piper/buttonspage.py, piper/leddialog.py, piper/ratbagd.py, piper/resolutionspage.py
This includes the switch to proper enums, so there's a bunch of
search/replaces included.
The ratbagd change happend quite a while ago, we just haven't synced in ages.
=> Sync ratbagd.py from libratbagd

.gitignore, data/check-files-in-git.sh, data/check-svg-in-meson.build.sh, data/meson.build, data/svg-lookup-ini-test.py, data/svgs/svg-lookup.ini
And two more tests so the svg files are in git and added to meson.build.
Fixes #368
=> Add a test for the svg-lookup

data/svgs/svg-lookup.ini
See https://github.com/libratbag/libratbag/pull/806
=> Add missing MX master PID

data/svgs/svg-lookup.ini
=> data: use the G9 svg for the G9x

data/meson.build, data/svgs/logitech-mx-master-3.svg
MX Master 3 and 2s have the same button layout but slightly different shape. Use 2s svg for now.
=> Add Logitech MX Master 3 SVG

po/LINGUAS, po/be.po
Initial Belarusian translation
=> Add Belarusian translation

data/meson.build, data/svgs/logitech-g602.svg, data/svgs/svg-lookup.ini
After the amazing work that @markusressel did with the G604, I took that file and made some slight modifications to create an svg for the G602.
I would venture to guess that this PR is dependent on https://github.com/libratbag/libratbag/pull/838
=> G602 now uses the G604 svg

data/meson.build, data/svgs/steelseries-kinzu-v3.svg, data/svgs/svg-lookup.ini
Since we got added support for the device [here](https://github.com/libratbag/libratbag/commit/fe1308fe389fab138087207efc3fd70a1ce3863c#diff-3bcc2baa5829bf4f08ae6bd4e231997a)
=> Add SVG for steelseries-kinzu-v3

po/LINGUAS, po/zh_TW.po
I added zh_TW translations, please review and merge it :smiley:
=> Add zh_TW translations.

data/meson.build, data/svgs/roccat-kone-pure.svg, data/svgs/svg-lookup.ini
Basically took @hipnoizz's design from #326, replaced the LED logo with the one from the G403 and removed the up & down buttons for the scroll wheel.
Signed-off-by: Stephan Lachnit <stephanlachnit@protonmail.com>
=> Add SVG for Roccat Kone Pure

data/svgs/svg-lookup.ini
Signed-off-by: Filipe Laíns <lains@archlinux.org>
=> data: add G305

.gitignore
See https://github.com/libratbag/libratbag/pull/871.
=> remove .gitignore

data/svgs/svg-lookup.ini
See https://github.com/libratbag/piper/issues/456
=> data: add wired ID of the G502 Hero Wireless

data/svgs/svg-lookup.ini
=> data: add G403 hero

.circleci/config.yml
Signed-off-by: Filipe Laíns <lains@archlinux.org>
=> ci: add arch

.github/ISSUE_TEMPLATE/bug_report.md
Signed-off-by: Filipe Laíns <lains@archlinux.org>
=> github: add device field to bug report template

data/svgs/svg-lookup.ini
=> Add additional G9x USB ID

data/svgs/svg-lookup.ini
added another ID for Logitech MX Anywhere 2
=> data: add missing ID for Logitech MX Anywhere 2

.circleci/config.yml
See https://github.com/libratbag/libratbag/pull/1002
=> Ubuntu 20.04

data/meson.build, meson.build, meson_options.txt
It should be possible to skip tests. Taken from
https://github.com/libratbag/libratbag/blob/e55b04ec7d41e4566ad585174ef6db108cb2804d/meson.build#L364-L365
=> meson: make tests optional

data/svgs/svg-lookup.ini
https://github.com/libratbag/libratbag/pull/1030
=> dataL: add another device ID for G203

data/ui/ButtonDialog.ui, piper/buttondialog.py
=> Don't close/accept macro dialog on esc/enter to allow binding these keys

po/de.po
I found a number of errors in the German translation and fixed them. There are a few opinionated changes, too.
=> translation: fix and improve German strings

data/meson.build, data/org.freedesktop.Piper-symbolic.svg, data/org.freedesktop.Piper.svg
=> app icon: update style, add source file, add symbolic

data/meson.build, data/svgs/logitech-g-pro-x-wireless-superlight.svg, data/svgs/svg-lookup.ini
Fixes #623, using the device id's from https://github.com/libratbag/libratbag/pull/1122
=> Re-Add Logitech G Pro X Superlight

data/meson.build, data/svgs/steelseries-senseiten.svg, data/svgs/svg-lookup.ini
Based on the svg from the Sensei RAW as they look virtually identical.
The Ten just has one more LED on the scrollwheel.
Depends on https://github.com/libratbag/libratbag/pull/1184
=> Add SteelSeries Sensei Ten

data/svgs/svg-lookup.ini
For https://github.com/libratbag/libratbag/commit/9fc6d12486414f94ca78e004a390d54d14c89dee, but let's wait for https://github.com/libratbag/libratbag/pull/1011 first.
=> data: add additional USB-ID for Roccat Kone Pure

org.freedesktop.Piper.json
And replace a meson option with one that actually exists
=> flatpak: sync the flatpak file with the one from flathub

data/org.freedesktop.Piper.appdata.xml.in.in
No 100% correct but it's less confusing than the previous blurb.
=> appdata: change to "Gaming mouse configuration utility"

data/ui/ResolutionsPage.ui, piper/resolutionspage.py
Fixes https://github.com/libratbag/piper/issues/674
=> add 125 and 250 rates

data/svgs/logitech-mx-anywhere3.svg, data/svgs/svg-lookup.ini
Same as #708, just rebased to avoid the merge and related detritus
Closes #708
=> data: add Logitech MX Anywhere 3 with single configuration for USB/Bluetooh

data/svgs/logitech-mx-vertical.svg
The old SVG was hastily made, and was a pain to work with.
This new SVG is organized, cleaned, and easier to look at.
Closes #710
=> Updated logitech-mx-vertical.svg

data/svgs/sn-tech-t3.svg, data/svgs/svg-lookup.ini
The SN TECH T3 is a very obscure mouse from about a half decade or so ago.
I had it laying around, and added it.
There are some issues with its configuration, but that is another story.
=> Add SN TECH T3 Gaming Mouse

piper/window.py
I don't know if this is a problem with my WM configuration, but I don't have a window icon in the task list, and this patch fixes it.
=> window: enable window icon

data/svgs/logitech-g900.svg
=> fix(g903): added second led to SVG

data/svgs/logitech-mx-anywhere2.svg
I modified the MX Anywhere 2 left and right buttons to have a better shape.
=> Better looking buttons for MX Anywhere 2

meson.build
CC https://github.com/libratbag/libratbag/issues/1388
=> build: bump ratbagd DBus API version

piper/buttondialog.py, piper/buttonspage.py, piper/ratbagd.py
libratbag back-end part - https://github.com/libratbag/libratbag/pull/1368
=> implement key bindings feature

data/ui/ResolutionRow.ui, piper/mouseperspective.py, piper/profilerow.py, piper/ratbagd.py, piper/resolutionrow.py
This PR does two main things:
- Redesign the ResolutionRow glade file to support disabling a resolution and setting a y-resolution
- Implement the DBus support for this
Requires libratbag/libratbag#870 to be merged.
=> ResolutionRow Redesign

data/svgs/svg-lookup.ini
Additional usb id for Logitech G102
=> Additional usb id for Logitech G102

data/svgs/logitech-mx-master-3s.svg, data/svgs/svg-lookup.ini
Tested + working
See my pullrequest for the libratbag support: https://github.com/libratbag/libratbag/pull/1346
=> Device added: Logitech MX Master 3S

data/piper.gresource.xml.in, data/ui/AdvancedPage.ui, piper/advancedpage.py, piper/mouseperspective.py, piper/ratbagd.py
Fixes https://github.com/libratbag/piper/issues/749
=> Add a new page with debounce and angle snapping

piper/buttondialog.py, piper/buttonspage.py
Probably not the best way design-wise, but it works and we can always iterate upon this.
Supersedes and closes #505, fixes #247.
=> buttonsdialog: implement button disabling

piper/ratbagd.py
This fixes regression of commit button not becoming active introduced by me in d390f22210bd317a58bea1996df6c0b3aba58b3c (#853).
=> ratbagd.py: connect to notify::dirty of child objects in the profile

piper/buttonspage.py, piper/ratbagd.py
Following https://github.com/libratbag/libratbag/pull/1455
=> tools: fix displaying of macros with mouse buttons in them

piper/mouseperspective.py, piper/profilerow.py, piper/ratbagd.py
Fixes #859.
To be honest, I don't really like the profile delete/add approach, as at the very least it's not the way libratbag works.
Note to myself: check why was it implemented this way instead of disabling/enabling.
=> Fix update profile list on disabling

piper/application.py, piper/buttondialog.py, piper/buttonspage.py, piper/mousemap.py, piper/mouseperspective.py, piper/resolutionspage.py
I think I was planning to check *all* of the type hints, but never got around to it and only checked a portion of them. Either way, this is already an improvement.
=> Improve some type hints

data/meson.build, meson.build, org.freedesktop.Piper.json
Our in-tree flatpak file (arguably no longer needed) is well out of date, let's sync it with the flathub one.
=> Sync the flatpak json

data/svgs/glorious-model-d.svg, data/svgs/svg-lookup.ini
Hello,
Can you please considere adding glorious model D svg file.
=> add glorious model-d svg

data/svgs/asus-rog-keris-wireless-aimpoint.svg, data/svgs/svg-lookup.ini
This has been tested on Arch Linux with my personal mouse, the corresponding libratbag PR has also been submitted.
=> added svg for asus rog keris wireless aimpoint

data/svgs/asus-rog-harpe-wireless.svg, data/svgs/svg-lookup.ini
Adds link to default asus moouse for rog harpe
=> add svg for asus rog harpe wireless
